$(warning "USE_PREBUILT_KERNEL: true, Using kernel prebuilts.")
KERNEL_PREBUILTS_PATH := device/oneplus/aston-kernel
TARGET_NO_KERNEL_OVERRIDE := true
BOARD_KERNEL_BINARIES := kernel
BOARD_PREBUILT_DTBOIMAGE := $(KERNEL_PREBUILTS_PATH)/dtbo.img
TARGET_PREBUILT_KERNEL := $(KERNEL_PREBUILTS_PATH)/kernel
TARGET_PREBUILT_DTB := $(KERNEL_PREBUILTS_PATH)/dtb.img
PRODUCT_COPY_FILES += \
    $(TARGET_PREBUILT_KERNEL):kernel \
	$(TARGET_PREBUILT_DTB):dtb.img

BOARD_SYSTEM_KERNEL_MODULES := $(wildcard $(KERNEL_PREBUILTS_PATH)/system_dlkm/*.ko)
BOARD_VENDOR_KERNEL_MODULES := $(wildcard $(KERNEL_PREBUILTS_PATH)/vendor_dlkm/*.ko)
BOARD_VENDOR_RAMDISK_KERNEL_MODULES := $(wildcard $(KERNEL_PREBUILTS_PATH)/vendor_ramdisk/*.ko)
BOARD_VENDOR_KERNEL_MODULES_BLOCKLIST_FILE := $(TARGET_KERNEL_SOURCE)/modules.vendor_blocklist.msm.kalama
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_BLOCKLIST_FILE := $(BOARD_VENDOR_KERNEL_MODULES_BLOCKLIST_FILE)
BOARD_SYSTEM_KERNEL_MODULES_LOAD := $(strip $(shell cat $(KERNEL_PREBUILTS_PATH)/system_dlkm/modules.load))
BOARD_VENDOR_KERNEL_MODULES_LOAD := $(strip $(shell cat $(KERNEL_PREBUILTS_PATH)/vendor_dlkm/modules.load))
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD := $(strip $(shell cat $(KERNEL_PREBUILTS_PATH)/vendor_ramdisk/modules.load))
BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD := $(strip $(shell cat $(KERNEL_PREBUILTS_PATH)/vendor_ramdisk/modules.load.recovery))
BOOT_KERNEL_MODULES := $(BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD)
SYSTEM_KERNEL_MODULES := $(BOARD_SYSTEM_KERNEL_MODULES_LOAD)
